[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "411p2YeAVu4pQQkP25Nhu6G3gNBjQ1Bs8A5V3g6ujmsf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
